<?php

/**
 * Short description for file
 *
 * Long description for file (if any)...
 *
 * PHP version 5
 *
 * Copyright (C) Maldives Hajj Corporation Limited - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 *
 * @category   Pilgrims Management System
 * @package    API Server
 * @author     Mohamed Nazim ict@mhcl.mv
 * @authored   12/15/2016 6:38 AM
 * @copyright  2016 Maldives Hajj Corporation Limited
 * @license    Closed Source.
 *
 * File name: WebUser.php
 */
class WebUser extends CWebUser {

  public $loginUrl = ['site/verify'];

  public function __get($name) {
    if (!$this->getIsGuest())
    {
      $person = Persons::model()->findByPk($this->getState('__id'));
      if (!empty($person)) {
        if (in_array($name, $person->attributeNames()) || in_array($name,
          array_keys($person->relations()))) {
          return $person->$name;
        }

      }
    }
    return parent::__get($name); // TODO: Change the autogenerated stub
  }

}